---
title: "mort_modelling"
output: html_document
---

```{r include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)

improve_data <- readxl::read_excel(here("Data/lifetable_data.xlsx"), sheet = "Improvement Factors 2020-22", skip = 2) |> 
  janitor::clean_names() |> 
  rename(male_25_year = x25_year_2, male_125_year = x125_year_3, female_25_year = x25_year_4, female_125_year = x125_year_5)

male_lifetable <- readxl::read_excel(here("data/lifetable_data.xlsx"), sheet = "ALT 2020-22 Males", skip = 1) |> 
  janitor::clean_names()

female_lifetable <- readxl::read_excel(here("data/lifetable_data.xlsx"), sheet = "ALT 2020-22 Females", skip = 1) |> 
  janitor::clean_names()

act_mort <- read_table(here("data/act_Mx_1x1.txt"), skip = 1) |> janitor::clean_names() |>   
  select(year, age, female, male) |> 
  mutate(age = as.integer(age), female = as.double(female), male = as.double(male))
nsw_mort <- read_table(here("data/nsw_Mx_1x1.txt"), skip = 1) |> janitor::clean_names() |>   
  select(year, age, female, male) |> 
  mutate(age = as.integer(age), female = as.double(female), male = as.double(male))
nt_mort <- read_table(here("data/nt_Mx_1x1.txt"), skip = 1) |> janitor::clean_names() |>   
  select(year, age, female, male) |> 
  mutate(age = as.integer(age), female = as.double(female), male = as.double(male))
qld_mort <- read_table(here("data/qld_Mx_1x1.txt"), skip = 1) |> janitor::clean_names() |>   
  select(year, age, female, male) |> 
  mutate(age = as.integer(age), female = as.double(female), male = as.double(male))
sa_mort <- read_table(here("data/sa_Mx_1x1.txt"), skip = 1) |> janitor::clean_names() |>   
  select(year, age, female, male) |> 
  mutate(age = as.integer(age), female = as.double(female), male = as.double(male))
tas_mort <- read_table(here("data/tas_Mx_1x1.txt"), skip = 1) |> janitor::clean_names() |>   
  select(year, age, female, male) |> 
  mutate(age = as.integer(age), female = as.double(female), male = as.double(male))
vic_mort <- read_table(here("data/vic_Mx_1x1.txt"), skip = 1) |> janitor::clean_names() |>   
  select(year, age, female, male) |> 
  mutate(age = as.integer(age), female = as.double(female), male = as.double(male))
wa_mort <- read_table(here("data/wa_Mx_1x1.txt"), skip = 1) |> janitor::clean_names() |>   
  select(year, age, female, male) |> 
  mutate(age = as.integer(age), female = as.double(female), male = as.double(male))

mort_data <- list(act = act_mort, nsw = nsw_mort, nt = nt_mort, qld = qld_mort, sa = sa_mort, tas = tas_mort, vic = vic_mort, wa = wa_mort)
```


# Extracting male and female matrices

```{r}
get_mort_matrices <- function(death_rate_df) {
  list(
    male = death_rate_df |> 
      select(-female) |> 
      pivot_wider(
        names_from = year,
        values_from = male,
        ) |> 
      filter(!is.na(age)) |> 
      arrange(age) |> 
      column_to_rownames("age") |> 
      as.matrix(),
    
    female = death_rate_df |> 
      select(-female) |> 
      pivot_wider(
        names_from = year,
        values_from = male,
        ) |> 
      filter(!is.na(age)) |> 
      arrange(age) |> 
      column_to_rownames("age") |> 
      as.matrix()
  )
}

mx_list <- lapply(mort_data, get_mort_matrices)
```


```{r}

```
















