---
title: "mort_modelling_simple"
output: html_document
---

```{r include=FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = TRUE)

source(here::here("Scripts/config.R"))
source(here::here("Scripts/helper_functions.R"))

improve_data <- dbReadTable(
  config$con, 
  Id(schema = "raw", table = "improvement_factors_2020-22")
  ) |> 
  janitor::clean_names() |> 
  dplyr::select(
    age, 
    male_25_year = x_25_year, 
    male_125_year = x_125_year, 
    female_25_year = x_125_year, 
    female_125_year = x_125_year2
    )

male_lifetable <- dbGetQuery(
  config$con,
  "SELECT Age, qx FROM [raw].[males_mortality_2020_22]"
) |> 
  janitor::clean_names() |> 
  drop_na()

female_lifetable <- dbGetQuery(
  config$con,
  "SELECT Age, qx FROM [raw].[females_mortality_2020_22]"
) |> 
  janitor::clean_names() |> 
  drop_na()
```

# Current Assumptions

- Minimum age to retire at (50 years)
- Maximum age of death (110 years)
- These imply a 60 year forecast horizon
- Each year, the horizon needs to be extended another year, if all other parameters stay constant

# Upgrades

- Can make mortality be based given survived to retirement age (rather than current age)


```{r}
# Improvement Rates for each age

improve_rates <- improve_data |> 
  dplyr::select(age, male_125_year, female_125_year) |> 
  mutate(male_125_year = (100 + male_125_year)/100, 
         female_125_year = (100 + female_125_year)/100)
```


```{r}
# Base Mortality Rates

male_qx <- male_lifetable |> 
  bind_rows(data.frame(age = 110, qx = 1))
female_qx <- female_lifetable |> 
  bind_rows(data.frame(age = 110, qx = 1))
```


```{r}
# Forecasted Mortality Rates

male_qx_forecast <- matrix(data = male_qx$qx, nrow = 111, ncol = config$period_years+4, byrow = FALSE)
rownames(male_qx_forecast) <- 0:110
female_qx_forecast <- matrix(data = female_qx$qx, nrow = 111, ncol = config$period_years+4, byrow = FALSE)
rownames(female_qx_forecast) <- 0:110

for(j in 2:ncol(male_qx_forecast)){
  
  male_qx_forecast[,j] <- male_qx_forecast[,j-1]*improve_rates$male_125_year
  female_qx_forecast[,j] <- female_qx_forecast[,j-1]*improve_rates$female_125_year
}

male_mortality_df <- male_qx_forecast |> 
  as.data.frame() |> 
  dplyr::select(-(1:3))

colnames(male_mortality_df) <- seq(2026, 2026 + config$period_years)

female_mortality_df <- female_qx_forecast |> 
  as.data.frame() |> 
  dplyr::select(-(1:3))

colnames(female_mortality_df) <- seq(2026, 2026 + config$period_years)
```

```{r}
mortality_df <- male_mortality_df |> 
  rownames_to_column(var = "age") |> 
  mutate(age = as.numeric(age),
         sex = "male") |> 
  bind_rows(
    female_mortality_df |> 
      rownames_to_column(var = "age") |> 
      mutate(age = as.numeric(age),
             sex = "female") 
  ) |> 
  dplyr::select(sex, age, everything()) |> 
  gather(-c(sex, age), key = "year", value = "mortality") |> 
  mutate(
    year = as.numeric(year),
    current_age = age - (year - 2026)
    ) |> 
  filter(current_age >= 50) |> 
  dplyr::select(sex, current_age, year, mortality)

dbWriteTable(config$con, 
             Id(schema = "processed", table = "mortality"), 
             mortality_df, 
             overwrite = TRUE)
```


```{r}
# Cumulative Survival Matrix

male_survival_df <- 1 - male_mortality_df
rownames(male_survival_df) <- 0:110

male_cum_survival_df <- data.frame(matrix(NA, nrow = config$period_years+1, ncol = config$period_years+1))
rownames(male_cum_survival_df) <- config$minimum_retirement:110
colnames(male_cum_survival_df) <- seq(2026, 2026 + config$period_years)

male_cum_survival_list <- as.list(rep(NA, config$retirement_window))

for(z in 1:config$retirement_window){
  
  male_cum_survival_list[[z]] <- male_cum_survival_df[, z:(config$period_years+1)]
  male_cum_survival_list[[z]][,1] <- male_survival_df[config$minimum_retirement:110,z]
  
  for(j in 2:ncol(male_cum_survival_list[[z]] )){
    for(i in 2:nrow(male_cum_survival_list[[z]] )){

      if(i < j){
        male_cum_survival_list[[z]][i,j] <- NA
        
      } else {
        male_cum_survival_list[[z]][i,j] <- male_cum_survival_list[[z]][i-1,j-1] * male_survival_df[i + config$minimum_retirement - 1,j]
      } 
      
    }
  }
    
}

names(male_cum_survival_list) <- 2026:2046
```


```{r}
# Cumulative Survival Matrix

female_survival_df <- 1 - female_mortality_df
rownames(female_survival_df) <- 0:110

female_cum_survival_df <- data.frame(matrix(NA, nrow = config$period_years+1, ncol = config$period_years+1))
rownames(female_cum_survival_df) <- config$minimum_retirement:110
colnames(female_cum_survival_df) <- seq(2026, 2026 + config$period_years)

female_cum_survival_list <- as.list(rep(NA, config$retirement_window))

for(z in 1:config$retirement_window){
  
  female_cum_survival_list[[z]] <- female_cum_survival_df[, z:config$period_years+1]
  female_cum_survival_list[[z]][,1] <- female_survival_df[config$minimum_retirement:110,z]
  
  for(j in 2:ncol(female_cum_survival_list[[z]] )){
    for(i in 2:nrow(female_cum_survival_list[[z]] )){

      if(i < j){
        female_cum_survival_list[[z]][i,j] <- NA
        
      } else {
        female_cum_survival_list[[z]][i,j] <- female_cum_survival_list[[z]][i-1,j-1] * female_survival_df[i+config$minimum_retirement-1,j]
      } 
      
    }
  }
    
}

names(female_cum_survival_list) <- 2026:2046
```


```{r}
# Combining into tidy data-frame.
# Involves wrangling matrix into tidy format, and creating combinations of starting age and retirement age.

set.seed(123)

mort_simulations <- lapply(male_cum_survival_list, function(x) calculate_death_years(x, death_rand = runif(1))) |> 
    bind_rows() |> 
    mutate(sim_id = 1, sex = "male") |> 
  bind_rows(
    lapply(female_cum_survival_list, function(x) calculate_death_years(x, death_rand = runif(1))) |> 
    bind_rows() |> 
    mutate(sim_id = 1, sex = "female")
  )

pb <- txtProgressBar(min = 0, max = config$sims, style = 3)

for(i in 2:config$sims){
  
  death_rand = runif(1)
  
  m <- lapply(male_cum_survival_list, function(x) calculate_death_years(x, death_rand = death_rand)) |> 
    bind_rows() |> 
    mutate(sim_id = i, sex = "male")
  
  f <- lapply(female_cum_survival_list, function(x) calculate_death_years(x, death_rand = death_rand)) |> 
    bind_rows() |> 
    mutate(sim_id = i, sex = "female")
  
  mort_simulations <- mort_simulations |> 
    bind_rows(m,f)
  
  setTxtProgressBar(pb, i)
}

close(pb)

# write.csv(mort_simulations, here("Data/Processed Data/simulations.csv"))

dbWriteTable(config$con, 
             Id(schema = "processed", table = "mortality_simulations"), 
             mort_simulations, 
             overwrite = TRUE
             )
```


```{r}
knitr::purl("mortality_modelling.Rmd", here::here("Scripts/mortality_modelling.R"))
```
