---
title: "retirement_forecast_script"
output: html_document
---

```{r}
knitr::opts_chunk$set(echo = TRUE)

source(here::here("Scripts/config.R"))
source(here::here("Scripts/helper_functions.R"))

super_forecast_calc <- dbReadTable(
  config$con, 
  Id(schema = "processed", table = "super_simulations")
  ) |> 
  mutate(
    across(-sim_id,~ 1 / (.x + 1) )
    ) |> 
  arrange(sim_id)

mort_sims <- dbReadTable(
  config$con, 
  Id(schema = "processed", table = "mortality_simulations")
  ) |> 
  mutate(invest_start_date = 2026 + retirement_age - starting_age) |> 
  dplyr::select(sim_id, sex, starting_age, retirement_age, invest_start_date, death_year) |> 
  arrange(sim_id)
```

```{r}
balanced <- super_forecast_calc |> dplyr::select(contains("balanced"))
growth <- super_forecast_calc |> dplyr::select(contains("growth"))
conservative <- super_forecast_calc |> dplyr::select(contains("conservative"))

pa_invests <- list(balanced = balanced, growth = growth, conservative = conservative)
```

```{r}
# Calculating annuity and terminal scale factors for each simulation

balanced_terminal <- numeric(nrow(mort_sims))
growth_terminal <- numeric(nrow(mort_sims))
conservative_terminal <- numeric(nrow(mort_sims))

balanced_annuity <- numeric(nrow(mort_sims))
growth_annuity <- numeric(nrow(mort_sims))
conservative_annuity <- numeric(nrow(mort_sims))
```

```{r}
pb <- txtProgressBar(min = 0, max = nrow(mort_sims), style = 3)

for(i in 1:nrow(mort_sims)){

  start_year_index <- as.numeric(mort_sims[i,"invest_start_date"] - config$start_year) + 1 # Grabs matrix index based on retirement year
  end_year_index <- as.numeric(mort_sims[i,"death_year"] - config$start_year) + 1 # Grabs matrix index based on death year
  sim_id <- as.numeric(mort_sims[i,"sim_id"]) # Gets the relevant simulation, which is the row number for the investment paths
  
  balanced_discount_path <- pa_invests$balanced[sim_id,start_year_index:end_year_index] |> 
    unlist(use.names = FALSE) |> 
    as.numeric() |> 
    cumprod()
  balanced_annuity[i] <- sum(balanced_discount_path) # Sums cumulative discount values to get annuity factor
  balanced_terminal[i] <- tail(balanced_discount_path, n = 1) # Selects last cumulative discount value for terminal estate factor
  
  growth_discount_path <- pa_invests$growth[sim_id,start_year_index:end_year_index] |> 
    unlist(use.names = FALSE) |> 
    as.numeric() |> 
    cumprod()
  growth_annuity[i] <- sum(growth_discount_path)
  growth_terminal[i] <- tail(growth_discount_path, n = 1)
  
  conservative_discount_path <- pa_invests$conservative[sim_id,start_year_index:end_year_index] |> 
    unlist(use.names = FALSE) |> 
    as.numeric() |> 
    cumprod()
  conservative_annuity[i] <- sum(conservative_discount_path)
  conservative_terminal[i] <- tail(conservative_discount_path, n = 1)
  
  setTxtProgressBar(pb, i)
}

close(pb)
```


```{r}
# Combining calculations into one data frame, and wrangling into a tidy structure for Power BI reporting.

combined_simulations <- mort_sims |> 
  mutate(balanced_annuity = balanced_annuity,
            balanced_terminal = balanced_terminal,
            growth_annuity = growth_annuity,
            growth_terminal = growth_terminal,
            conservative_annuity = conservative_annuity,
            conservative_terminal = conservative_terminal) |> 
  pivot_longer(cols = balanced_annuity:conservative_terminal,
               names_to = c("risk_profile", "type"),
               names_sep = "_",
               values_to = "value") |>
  distinct(sim_id, sex, starting_age, retirement_age, risk_profile, type, .keep_all = TRUE) |> 
  pivot_wider(names_from = type,
              values_from = value)

dbWriteTable(config$con, 
             Id(schema = "processed", table = "retirement_simulations"), 
             combined_simulations, 
             overwrite = TRUE)
```

```{r}
knitr::purl("retirement_data.Rmd", here::here("Scripts/retirement_data.R"))
```


















